
package project1;

import java.awt.event.KeyEvent;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.*;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.Iterator;
import java.util.TreeSet;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author HEMANT MARVE
 */
public class NewJFrame extends javax.swing.JFrame {
    String r,n,m;
  DefaultTableModel model;
    double a;

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
        nonactive();
        Insert.setVisible(false);
       
        
    model=(DefaultTableModel)jTable1.getModel(); //castinf jtabel to default
    }
    public void nonactive()
    {
         sbar.setVisible(false);
    //sbar.setEnabled(false);
    //Menu.setVisible(true);
    //Menu.setEnabled(false);
   }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Main = new javax.swing.JPanel();
        LOGIN = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JPasswordField();
        jLabel42 = new javax.swing.JLabel();
        Menu = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        sbar = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel92 = new javax.swing.JLabel();
        Attendance = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel93 = new javax.swing.JLabel();
        Dues = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel77 = new javax.swing.JLabel();
        jLabel78 = new javax.swing.JLabel();
        jLabel94 = new javax.swing.JLabel();
        Assignment = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel76 = new javax.swing.JLabel();
        Marks = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        Settings = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        jLabel73 = new javax.swing.JLabel();
        jLabel74 = new javax.swing.JLabel();
        jTextField20 = new javax.swing.JTextField();
        jTextField21 = new javax.swing.JTextField();
        jTextField22 = new javax.swing.JTextField();
        jLabel75 = new javax.swing.JLabel();
        jLabel95 = new javax.swing.JLabel();
        Editor = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel79 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        Delete = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel90 = new javax.swing.JLabel();
        Result = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        jLabel85 = new javax.swing.JLabel();
        jLabel88 = new javax.swing.JLabel();
        SearchData = new javax.swing.JPanel();
        jLabel44 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton7 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel46 = new javax.swing.JLabel();
        INSERTDUES = new javax.swing.JPanel();
        jLabel80 = new javax.swing.JLabel();
        jLabel81 = new javax.swing.JLabel();
        jTextField23 = new javax.swing.JTextField();
        jLabel82 = new javax.swing.JLabel();
        jLabel83 = new javax.swing.JLabel();
        jTextField24 = new javax.swing.JTextField();
        jLabel86 = new javax.swing.JLabel();
        jLabel91 = new javax.swing.JLabel();
        Update = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jTextField15 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jTextField16 = new javax.swing.JTextField();
        jTextField17 = new javax.swing.JTextField();
        jTextField18 = new javax.swing.JTextField();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jTextField19 = new javax.swing.JTextField();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel87 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        Insert = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel84 = new javax.swing.JLabel();
        jLabel89 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(650, 581));
        setResizable(false);

        Main.setLayout(new java.awt.CardLayout());

        LOGIN.setBackground(new java.awt.Color(102, 0, 0));
        LOGIN.setLayout(null);

        jButton1.setFont(new java.awt.Font("Palatino Linotype", 3, 14)); // NOI18N
        jButton1.setText("LOGIN");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        LOGIN.add(jButton1);
        jButton1.setBounds(330, 310, 84, 34);

        jLabel1.setFont(new java.awt.Font("Arial Unicode MS", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("USER NAME:");
        LOGIN.add(jLabel1);
        jLabel1.setBounds(170, 160, 140, 36);

        jLabel2.setFont(new java.awt.Font("Arial Unicode MS", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("PASSWORD:");
        LOGIN.add(jLabel2);
        jLabel2.setBounds(180, 230, 140, 36);

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        LOGIN.add(jTextField2);
        jTextField2.setBounds(350, 160, 161, 30);

        jLabel12.setBackground(new java.awt.Color(0, 153, 255));
        jLabel12.setFont(new java.awt.Font("Palatino Linotype", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 204, 204));
        LOGIN.add(jLabel12);
        jLabel12.setBounds(120, 360, 435, 34);
        LOGIN.add(jTextField3);
        jTextField3.setBounds(350, 230, 161, 33);

        jLabel42.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project1/fp.png"))); // NOI18N
        jLabel42.setText("jLabel42");
        LOGIN.add(jLabel42);
        jLabel42.setBounds(0, 0, 810, 580);

        Main.add(LOGIN, "card2");

        Menu.setBackground(new java.awt.Color(0, 0, 153));
        Menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuMouseClicked(evt);
            }
        });
        Menu.setLayout(null);

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Stencil", 3, 18)); // NOI18N
        jButton2.setText("ATTENDANCE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        Menu.add(jButton2);
        jButton2.setBounds(190, 40, 190, 100);

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setFont(new java.awt.Font("Stencil", 3, 18)); // NOI18N
        jButton3.setText("MARKS");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        Menu.add(jButton3);
        jButton3.setBounds(410, 40, 200, 100);

        jButton4.setBackground(new java.awt.Color(0, 0, 0));
        jButton4.setFont(new java.awt.Font("Stencil", 3, 18)); // NOI18N
        jButton4.setText("DUES");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        Menu.add(jButton4);
        jButton4.setBounds(190, 210, 190, 100);

        jButton5.setBackground(new java.awt.Color(255, 255, 255));
        jButton5.setFont(new java.awt.Font("Stencil", 3, 18)); // NOI18N
        jButton5.setText("ASSIGNMENTS");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        Menu.add(jButton5);
        jButton5.setBounds(410, 210, 200, 100);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project1/Menu.png"))); // NOI18N
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        Menu.add(jLabel7);
        jLabel7.setBounds(10, 10, 32, 32);

        sbar.setBackground(new java.awt.Color(0, 153, 153));
        sbar.setLayout(null);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project1/icons8_home_40px.png"))); // NOI18N
        jLabel9.setText("     HOME");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        sbar.add(jLabel9);
        jLabel9.setBounds(0, 50, 170, 40);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project1/icons8_passenger_with_baggage_40px.png"))); // NOI18N
        jLabel10.setText("SIGNOUT");
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        sbar.add(jLabel10);
        jLabel10.setBounds(0, 190, 170, 50);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project1/icons8_settings_3_40px.png"))); // NOI18N
        jLabel8.setText("SETTINGS");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        sbar.add(jLabel8);
        jLabel8.setBounds(-2, 110, 170, 70);

        jLabel11.setFont(new java.awt.Font("Wide Latin", 1, 18)); // NOI18N
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project1/icons8_clone_40px.png"))); // NOI18N
        jLabel11.setText("ABOUT");
        sbar.add(jLabel11);
        jLabel11.setBounds(0, 250, 169, 120);

        Menu.add(sbar);
        sbar.setBounds(0, 0, 170, 370);

        jLabel92.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project1/elec.png"))); // NOI18N
        jLabel92.setText("jLabel92");
        Menu.add(jLabel92);
        jLabel92.setBounds(0, 4, 650, 560);

        Main.add(Menu, "card3");

        Attendance.setBackground(new java.awt.Color(204, 204, 0));
        Attendance.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AttendanceMouseClicked(evt);
            }
        });
        Attendance.setLayout(null);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project1/back.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        Attendance.add(jLabel3);
        jLabel3.setBounds(0, 0, 32, 32);

        jLabel47.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(204, 204, 204));
        jLabel47.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project1/icons8_student_male_48px.png"))); // NOI18N
        jLabel47.setText("ATTENDANCE");
        Attendance.add(jLabel47);
        jLabel47.setBounds(237, 50, 200, 48);

        jLabel48.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(204, 204, 204));
        jLabel48.setText("PERCENTAGE :");
        Attendance.add(jLabel48);
        jLabel48.setBounds(115, 142, 140, 33);

        jLabel58.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel58.setForeground(new java.awt.Color(204, 204, 204));
        Attendance.add(jLabel58);
        jLabel58.setBounds(273, 142, 320, 33);

        jLabel93.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project1/fp.png"))); // NOI18N
        jLabel93.setText("jLabel93");
        Attendance.add(jLabel93);
        jLabel93.setBounds(0, -6, 700, 620);

        Main.add(Attendance, "card4");

        Dues.setBackground(new java.awt.Color(0, 153, 153));
        Dues.setLayout(null);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project1/back.png"))); // NOI18N
        jLabel4.setText("back");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        Dues.add(jLabel4);
        jLabel4.setBounds(0, 0, 34, 32);

        jLabel77.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel77.setForeground(new java.awt.Color(204, 204, 204));
        jLabel77.setText("DUES :");
        Dues.add(jLabel77);
        jLabel77.setBounds(210, 230, 62, 31);

        jLabel78.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel78.setForeground(new java.awt.Color(204, 204, 204));
        jLabel78.setText("0");
        Dues.add(jLabel78);
        jLabel78.setBounds(330, 230, 78, 31);

        jLabel94.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project1/fp.png"))); // NOI18N
        jLabel94.setText("jLabel94");
        Dues.add(jLabel94);
        jLabel94.setBounds(0, 0, 700, 620);

        Main.add(Dues, "card5");

        Assignment.setBackground(new java.awt.Color(204, 0, 204));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project1/back.png"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        jLabel76.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        javax.swing.GroupLayout AssignmentLayout = new javax.swing.GroupLayout(Assignment);
        Assignment.setLayout(AssignmentLayout);
        AssignmentLayout.setHorizontalGroup(
            AssignmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AssignmentLayout.createSequentialGroup()
                .addComponent(jLabel5)
                .addContainerGap(618, Short.MAX_VALUE))
            .addComponent(jLabel76, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        AssignmentLayout.setVerticalGroup(
            AssignmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AssignmentLayout.createSequentialGroup()
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jLabel76, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        Main.add(Assignment, "card7");

        Marks.setBackground(new java.awt.Color(204, 0, 204));
        Marks.setLayout(null);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project1/back.png"))); // NOI18N
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        Marks.add(jLabel6);
        jLabel6.setBounds(0, 0, 32, 32);

        jLabel59.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel59.setForeground(new java.awt.Color(204, 204, 204));
        jLabel59.setText("SUBJECT 1 :");
        Marks.add(jLabel59);
        jLabel59.setBounds(200, 60, 120, 30);

        jLabel60.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel60.setForeground(new java.awt.Color(204, 204, 204));
        jLabel60.setText("SUBJECT 2 :");
        Marks.add(jLabel60);
        jLabel60.setBounds(200, 110, 107, 29);

        jLabel61.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel61.setForeground(new java.awt.Color(204, 204, 204));
        jLabel61.setText("SUBJECT 3 :");
        Marks.add(jLabel61);
        jLabel61.setBounds(200, 160, 107, 26);

        jLabel62.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel62.setForeground(new java.awt.Color(204, 204, 204));
        jLabel62.setText("SUBJECT 4 :");
        Marks.add(jLabel62);
        jLabel62.setBounds(200, 210, 107, 27);

        jLabel63.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel63.setForeground(new java.awt.Color(204, 204, 204));
        jLabel63.setText("       TOTAL :");
        Marks.add(jLabel63);
        jLabel63.setBounds(200, 260, 120, 27);

        jLabel64.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel64.setForeground(new java.awt.Color(204, 204, 204));
        jLabel64.setText("PERCENTAGE :");
        Marks.add(jLabel64);
        jLabel64.setBounds(180, 310, 132, 26);

        jLabel65.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel65.setForeground(new java.awt.Color(204, 204, 204));
        Marks.add(jLabel65);
        jLabel65.setBounds(320, 70, 70, 25);

        jLabel66.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel66.setForeground(new java.awt.Color(204, 204, 204));
        Marks.add(jLabel66);
        jLabel66.setBounds(320, 110, 70, 30);

        jLabel67.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel67.setForeground(new java.awt.Color(204, 204, 204));
        Marks.add(jLabel67);
        jLabel67.setBounds(320, 160, 70, 26);

        jLabel68.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel68.setForeground(new java.awt.Color(204, 204, 204));
        Marks.add(jLabel68);
        jLabel68.setBounds(320, 260, 70, 30);

        jLabel69.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel69.setForeground(new java.awt.Color(204, 204, 204));
        Marks.add(jLabel69);
        jLabel69.setBounds(320, 210, 78, 27);

        jLabel70.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel70.setForeground(new java.awt.Color(204, 204, 204));
        Marks.add(jLabel70);
        jLabel70.setBounds(320, 310, 120, 26);

        jLabel45.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project1/fp.png"))); // NOI18N
        jLabel45.setText("jLabel45");
        Marks.add(jLabel45);
        jLabel45.setBounds(0, 0, 700, 570);

        Main.add(Marks, "card7");

        Settings.setBackground(new java.awt.Color(255, 102, 102));
        Settings.setLayout(null);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project1/back.png"))); // NOI18N
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });
        Settings.add(jLabel13);
        jLabel13.setBounds(0, 0, 32, 32);

        jLabel71.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel71.setText("OLD PASSWORD :");
        Settings.add(jLabel71);
        jLabel71.setBounds(157, 66, 124, 34);

        jLabel72.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel72.setText("NEW PASSWORD :");
        Settings.add(jLabel72);
        jLabel72.setBounds(168, 118, 129, 31);

        jLabel73.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel73.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project1/icons8_settings_3_40px.png"))); // NOI18N
        jLabel73.setText("SAVE");
        jLabel73.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel73MouseClicked(evt);
            }
        });
        Settings.add(jLabel73);
        jLabel73.setBounds(315, 259, 100, 40);

        jLabel74.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel74.setText("CONFIRM PASSWORD :");
        Settings.add(jLabel74);
        jLabel74.setBounds(133, 179, 164, 31);

        jTextField20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField20ActionPerformed(evt);
            }
        });
        Settings.add(jTextField20);
        jTextField20.setBounds(315, 66, 181, 30);
        Settings.add(jTextField21);
        jTextField21.setBounds(315, 118, 181, 30);
        Settings.add(jTextField22);
        jTextField22.setBounds(315, 175, 181, 30);

        jLabel75.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        Settings.add(jLabel75);
        jLabel75.setBounds(133, 341, 507, 35);

        jLabel95.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project1/(23).jpg"))); // NOI18N
        jLabel95.setText("jLabel95");
        Settings.add(jLabel95);
        jLabel95.setBounds(0, 0, 650, 580);

        Main.add(Settings, "card8");

        Editor.setBackground(new java.awt.Color(255, 153, 153));
        Editor.setLayout(null);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project1/back.png"))); // NOI18N
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });
        Editor.add(jLabel14);
        jLabel14.setBounds(0, 0, 32, 32);

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(204, 204, 204));
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project1/icons8_data_configuration_48px.png"))); // NOI18N
        jLabel15.setText("UPDATE");
        jLabel15.setMaximumSize(new java.awt.Dimension(80, 80));
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });
        Editor.add(jLabel15);
        jLabel15.setBounds(100, 130, 170, 64);

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(204, 204, 204));
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project1/icons8_view_file_48px.png"))); // NOI18N
        jLabel16.setText("SEARCH");
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
        });
        Editor.add(jLabel16);
        jLabel16.setBounds(361, 136, 150, 60);

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(204, 204, 204));
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project1/icons8_trash_48px.png"))); // NOI18N
        jLabel17.setText("DELETE");
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel17MouseClicked(evt);
            }
        });
        Editor.add(jLabel17);
        jLabel17.setBounds(90, 370, 140, 48);

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(204, 204, 204));
        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project1/icons8_database_restore_48px.png"))); // NOI18N
        jLabel23.setText("INSERT & Create ACCOUNT");
        jLabel23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel23MouseClicked(evt);
            }
        });
        Editor.add(jLabel23);
        jLabel23.setBounds(300, 370, 280, 48);

        jLabel79.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel79.setForeground(new java.awt.Color(204, 204, 204));
        jLabel79.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project1/icons8_data_configuration_48px.png"))); // NOI18N
        jLabel79.setText("DuES update & ENTER");
        jLabel79.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel79MouseClicked(evt);
            }
        });
        Editor.add(jLabel79);
        jLabel79.setBounds(200, 260, 270, 48);

        jLabel43.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project1/fp.png"))); // NOI18N
        jLabel43.setText("jLabel43");
        Editor.add(jLabel43);
        jLabel43.setBounds(0, 0, 750, 620);

        Main.add(Editor, "card9");

        Delete.setBackground(new java.awt.Color(0, 153, 153));
        Delete.setLayout(null);

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project1/back.png"))); // NOI18N
        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel18MouseClicked(evt);
            }
        });
        Delete.add(jLabel18);
        jLabel18.setBounds(0, 0, 32, 32);

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        Delete.add(jTextField4);
        jTextField4.setBounds(283, 81, 182, 31);

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(204, 204, 204));
        jLabel21.setText("Student Roll No. :");
        Delete.add(jLabel21);
        jLabel21.setBounds(105, 81, 170, 31);

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project1/icons8_trash_48px.png"))); // NOI18N
        jLabel22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel22MouseClicked(evt);
            }
        });
        Delete.add(jLabel22);
        jLabel22.setBounds(237, 162, 48, 48);

        jLabel40.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(204, 204, 204));
        Delete.add(jLabel40);
        jLabel40.setBounds(102, 250, 356, 28);

        jLabel41.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Delete.add(jLabel41);
        jLabel41.setBounds(102, 284, 356, 37);

        jLabel90.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project1/fp.png"))); // NOI18N
        jLabel90.setText("jLabel90");
        Delete.add(jLabel90);
        jLabel90.setBounds(0, -6, 760, 630);

        Main.add(Delete, "card10");

        Result.setBackground(new java.awt.Color(153, 153, 153));
        Result.setLayout(null);

        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project1/back.png"))); // NOI18N
        jLabel32.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel32MouseClicked(evt);
            }
        });
        Result.add(jLabel32);
        jLabel32.setBounds(0, 0, 32, 32);

        jLabel33.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(204, 204, 204));
        jLabel33.setText("Roll No. :");
        Result.add(jLabel33);
        jLabel33.setBounds(184, 16, 71, 30);

        jLabel34.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(204, 204, 204));
        jLabel34.setText("Subject 2:");
        Result.add(jLabel34);
        jLabel34.setBounds(184, 114, 71, 30);

        jLabel35.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(204, 204, 204));
        jLabel35.setText("Subject 3:");
        Result.add(jLabel35);
        jLabel35.setBounds(184, 164, 71, 30);

        jLabel36.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(204, 204, 204));
        jLabel36.setText("Subject 4:");
        Result.add(jLabel36);
        jLabel36.setBounds(184, 214, 71, 30);

        jTextField8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jTextField8MouseExited(evt);
            }
        });
        jTextField8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField8KeyTyped(evt);
            }
        });
        Result.add(jTextField8);
        jTextField8.setBounds(273, 66, 117, 30);

        jTextField9.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField9KeyTyped(evt);
            }
        });
        Result.add(jTextField9);
        jTextField9.setBounds(273, 116, 117, 30);

        jTextField10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField10ActionPerformed(evt);
            }
        });
        jTextField10.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField10KeyTyped(evt);
            }
        });
        Result.add(jTextField10);
        jTextField10.setBounds(273, 216, 117, 30);

        jTextField11.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField11KeyTyped(evt);
            }
        });
        Result.add(jTextField11);
        jTextField11.setBounds(273, 166, 117, 30);

        jLabel37.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(204, 204, 204));
        jLabel37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project1/icons8_save_48px.png"))); // NOI18N
        jLabel37.setText("Save");
        jLabel37.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel37MouseClicked(evt);
            }
        });
        Result.add(jLabel37);
        jLabel37.setBounds(358, 272, 100, 48);

        jLabel38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project1/icons8_student_male_48px.png"))); // NOI18N
        Result.add(jLabel38);
        jLabel38.setBounds(544, 28, 48, 48);

        jTextField12.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField12KeyTyped(evt);
            }
        });
        Result.add(jTextField12);
        jTextField12.setBounds(273, 18, 117, 30);

        jLabel39.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(204, 204, 204));
        jLabel39.setText("Subject 1:");
        Result.add(jLabel39);
        jLabel39.setBounds(184, 66, 71, 30);

        jLabel85.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel85.setForeground(new java.awt.Color(204, 204, 204));
        Result.add(jLabel85);
        jLabel85.setBounds(80, 280, 245, 48);

        jLabel88.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project1/fp.png"))); // NOI18N
        jLabel88.setText("jLabel88");
        Result.add(jLabel88);
        jLabel88.setBounds(0, 0, 840, 620);

        Main.add(Result, "card13");

        SearchData.setBackground(new java.awt.Color(0, 153, 153));
        SearchData.setLayout(null);

        jLabel44.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project1/back.png"))); // NOI18N
        jLabel44.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel44MouseClicked(evt);
            }
        });
        SearchData.add(jLabel44);
        jLabel44.setBounds(0, 0, 32, 32);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Roll No.", "Name", "Mobile", "Attendance", "DUES", "Subject1", "Subject2", "Subject3", "Subject4", "Total", "Percenteage"
            }
        ));
        jTable1.setColumnSelectionAllowed(true);
        jScrollPane1.setViewportView(jTable1);
        jTable1.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        SearchData.add(jScrollPane1);
        jScrollPane1.setBounds(10, 40, 630, 310);

        jButton7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton7.setText("Filter");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        SearchData.add(jButton7);
        jButton7.setBounds(260, 420, 80, 30);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Attendance", "Dues", "Marks", "Roll" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        SearchData.add(jComboBox1);
        jComboBox1.setBounds(250, 360, 100, 30);

        jLabel46.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project1/elec.png"))); // NOI18N
        jLabel46.setText("jLabel46");
        SearchData.add(jLabel46);
        jLabel46.setBounds(0, 0, 750, 660);

        Main.add(SearchData, "card14");

        INSERTDUES.setBackground(new java.awt.Color(0, 204, 102));
        INSERTDUES.setLayout(null);

        jLabel80.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project1/back.png"))); // NOI18N
        jLabel80.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel80MouseClicked(evt);
            }
        });
        INSERTDUES.add(jLabel80);
        jLabel80.setBounds(0, 0, 32, 32);

        jLabel81.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel81.setForeground(new java.awt.Color(204, 204, 204));
        jLabel81.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project1/icons8_student_male_48px.png"))); // NOI18N
        jLabel81.setText("DUES");
        INSERTDUES.add(jLabel81);
        jLabel81.setBounds(170, 110, 90, 48);

        jTextField23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField23ActionPerformed(evt);
            }
        });
        jTextField23.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField23KeyTyped(evt);
            }
        });
        INSERTDUES.add(jTextField23);
        jTextField23.setBounds(290, 120, 160, 20);

        jLabel82.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project1/icons8_save_48px.png"))); // NOI18N
        jLabel82.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel82MouseClicked(evt);
            }
        });
        INSERTDUES.add(jLabel82);
        jLabel82.setBounds(300, 200, 48, 48);

        jLabel83.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel83.setForeground(new java.awt.Color(204, 204, 204));
        jLabel83.setText("ROLL NO  :");
        INSERTDUES.add(jLabel83);
        jLabel83.setBounds(190, 50, 76, 17);

        jTextField24.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField24KeyTyped(evt);
            }
        });
        INSERTDUES.add(jTextField24);
        jTextField24.setBounds(290, 50, 159, 20);

        jLabel86.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel86.setForeground(new java.awt.Color(204, 204, 204));
        INSERTDUES.add(jLabel86);
        jLabel86.setBounds(200, 237, 274, 39);

        jLabel91.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project1/fp.png"))); // NOI18N
        jLabel91.setText("jLabel91");
        INSERTDUES.add(jLabel91);
        jLabel91.setBounds(0, -6, 650, 590);

        Main.add(INSERTDUES, "card15");

        Update.setBackground(new java.awt.Color(102, 102, 255));
        Update.setLayout(null);

        jLabel20.setForeground(new java.awt.Color(204, 204, 204));
        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project1/back.png"))); // NOI18N
        jLabel20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel20MouseClicked(evt);
            }
        });
        Update.add(jLabel20);
        jLabel20.setBounds(0, 0, 32, 32);

        jTextField15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField15ActionPerformed(evt);
            }
        });
        jTextField15.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField15KeyTyped(evt);
            }
        });
        Update.add(jTextField15);
        jTextField15.setBounds(409, 148, 231, 30);

        jTextField14.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField14KeyTyped(evt);
            }
        });
        Update.add(jTextField14);
        jTextField14.setBounds(10, 167, 227, 30);

        jLabel49.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(204, 204, 204));
        jLabel49.setText("UpDaTe ReSulT DaTa :");
        Update.add(jLabel49);
        jLabel49.setBounds(440, 103, 154, 27);

        jLabel50.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(204, 204, 204));
        jLabel50.setText("UpDaTe AtTeNdAnCe :");
        Update.add(jLabel50);
        jLabel50.setBounds(20, 126, 157, 30);

        jTextField16.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField16KeyTyped(evt);
            }
        });
        Update.add(jTextField16);
        jTextField16.setBounds(409, 189, 231, 29);

        jTextField17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField17ActionPerformed(evt);
            }
        });
        jTextField17.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField17KeyTyped(evt);
            }
        });
        Update.add(jTextField17);
        jTextField17.setBounds(409, 230, 231, 30);

        jTextField18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField18ActionPerformed(evt);
            }
        });
        jTextField18.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField18KeyTyped(evt);
            }
        });
        Update.add(jTextField18);
        jTextField18.setBounds(409, 266, 231, 30);

        jLabel51.setForeground(new java.awt.Color(204, 204, 204));
        jLabel51.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project1/icons8_save_48px.png"))); // NOI18N
        jLabel51.setText("UpDaTe AttEnDaNcE");
        jLabel51.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel51MouseClicked(evt);
            }
        });
        Update.add(jLabel51);
        jLabel51.setBounds(40, 240, 180, 48);

        jLabel52.setForeground(new java.awt.Color(204, 204, 204));
        jLabel52.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project1/icons8_save_48px.png"))); // NOI18N
        jLabel52.setText("UPdAtE ReSuLt");
        jLabel52.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel52MouseClicked(evt);
            }
        });
        Update.add(jLabel52);
        jLabel52.setBounds(430, 320, 150, 48);

        jTextField19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField19ActionPerformed(evt);
            }
        });
        jTextField19.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField19KeyTyped(evt);
            }
        });
        Update.add(jTextField19);
        jTextField19.setBounds(234, 62, 162, 30);

        jLabel53.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel53.setForeground(new java.awt.Color(204, 204, 204));
        jLabel53.setText("Enter Roll No. :");
        Update.add(jLabel53);
        jLabel53.setBounds(117, 60, 113, 30);

        jLabel54.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel54.setForeground(new java.awt.Color(204, 204, 204));
        jLabel54.setText("SUBJECT 1:");
        Update.add(jLabel54);
        jLabel54.setBounds(309, 153, 82, 17);

        jLabel55.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel55.setForeground(new java.awt.Color(204, 204, 204));
        jLabel55.setText("SUBJECT 2:");
        Update.add(jLabel55);
        jLabel55.setBounds(309, 193, 82, 17);

        jLabel56.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel56.setForeground(new java.awt.Color(204, 204, 204));
        jLabel56.setText("SUBJECT 3:");
        Update.add(jLabel56);
        jLabel56.setBounds(309, 235, 82, 17);

        jLabel57.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel57.setForeground(new java.awt.Color(204, 204, 204));
        jLabel57.setText("SUBJECT 4:");
        Update.add(jLabel57);
        jLabel57.setBounds(309, 266, 90, 38);

        jLabel87.setForeground(new java.awt.Color(204, 204, 204));
        Update.add(jLabel87);
        jLabel87.setBounds(104, 361, 300, 43);

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project1/fp.png"))); // NOI18N
        jLabel19.setText("jLabel19");
        Update.add(jLabel19);
        jLabel19.setBounds(0, 0, 780, 590);

        Main.add(Update, "card12");

        Insert.setBackground(new java.awt.Color(204, 0, 204));
        Insert.setForeground(new java.awt.Color(255, 255, 0));
        Insert.setLayout(null);

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project1/back.png"))); // NOI18N
        jLabel24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel24MouseClicked(evt);
            }
        });
        Insert.add(jLabel24);
        jLabel24.setBounds(0, 0, 32, 32);

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(204, 204, 204));
        jLabel25.setText("Roll NO. :");
        Insert.add(jLabel25);
        jLabel25.setBounds(143, 25, 100, 38);

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(204, 204, 204));
        jLabel26.setText("Name :");
        Insert.add(jLabel26);
        jLabel26.setBounds(145, 80, 80, 38);

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(204, 204, 204));
        jLabel27.setText("Attendance(%) :");
        Insert.add(jLabel27);
        jLabel27.setBounds(83, 138, 160, 38);

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(204, 204, 204));
        jLabel28.setText("Mobile No. :");
        Insert.add(jLabel28);
        jLabel28.setBounds(121, 200, 120, 38);

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        jTextField5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField5KeyTyped(evt);
            }
        });
        Insert.add(jTextField5);
        jTextField5.setBounds(261, 82, 194, 38);

        jTextField6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField6KeyTyped(evt);
            }
        });
        Insert.add(jTextField6);
        jTextField6.setBounds(261, 140, 194, 38);

        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        jTextField7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField7KeyTyped(evt);
            }
        });
        Insert.add(jTextField7);
        jTextField7.setBounds(261, 25, 194, 38);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1KeyTyped(evt);
            }
        });
        Insert.add(jTextField1);
        jTextField1.setBounds(261, 200, 194, 35);

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(204, 204, 204));
        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project1/icons8_student_male_48px.png"))); // NOI18N
        jLabel29.setText("RESULT DATA");
        jLabel29.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel29MouseClicked(evt);
            }
        });
        Insert.add(jLabel29);
        jLabel29.setBounds(340, 400, 150, 48);

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(204, 204, 204));
        jLabel30.setText("CLICK ICON ENTER RESULT:");
        Insert.add(jLabel30);
        jLabel30.setBounds(270, 360, 260, 30);

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(204, 204, 204));
        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project1/icons8_save_48px.png"))); // NOI18N
        jLabel31.setText("FIRST SAVE IT.");
        jLabel31.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel31MouseClicked(evt);
            }
        });
        Insert.add(jLabel31);
        jLabel31.setBounds(210, 260, 170, 48);

        jLabel84.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel84.setForeground(new java.awt.Color(204, 204, 204));
        Insert.add(jLabel84);
        jLabel84.setBounds(10, 260, 185, 48);

        jLabel89.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project1/fp.png"))); // NOI18N
        jLabel89.setText("jLabel89");
        Insert.add(jLabel89);
        jLabel89.setBounds(0, 0, 650, 580);

        Main.add(Insert, "card15");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        // jPanel1.setVisible(false);
        //jPanel3.setVisible(true);
        if("123".equals(jTextField3.getText())&&"operator".equals(jTextField2.getText()))
        {
            Main.removeAll();
        Main.add(Editor);
        Main.repaint();
        Main.revalidate();
        }
        else
        {
        try
        {
            //String b=jTextField2.getText();
        Statement stmt=(Project1.con).createStatement();
            String sql1="select * from Security where Roll='"+jTextField2.getText()+"'";
           // String c=jTextField3.getText();
            
               ResultSet rs=stmt.executeQuery(sql1);
               
           if(rs.next())
           {
        if(((rs.getString(1)).equals(jTextField2.getText()))&&((rs.getString(2)).equals(jTextField3.getText())))
        {
            r=jTextField2.getText();
            Main.removeAll();
        Main.add(Menu);
        Main.repaint();
        Main.revalidate();
        jTextField2.setText("");
        jTextField3.setText("");
        }
        else
        {
            
        jLabel12.setText("INVALID USER NAME OR PASSWORD");
        
        
        }
           }
        else
        {
            
        jLabel12.setText("INVALID USER NAME OR PASSWORD");
        
        
        }
        }
        catch(Exception e)
        {}
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        try
        {
            Statement stmt=(Project1.con).createStatement();
             String sql1="select * from Details where Roll='"+r+"'";
        ResultSet rs=stmt.executeQuery(sql1);
        rs.next();
        jLabel78.setText(rs.getString(5));
        }
        catch(Exception e)
        {}
        Main.removeAll();
        Main.add(Dues);
        Main.repaint();
        Main.revalidate();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try
        {
            ResultSet rs;
            Statement stmt=(Project1.con).createStatement();
            //String sql1="select * from Details where Roll='"+r+"'";
            rs=stmt.executeQuery("select * from Details where Roll='"+r+"'");   
                if(rs.next())
                {
                  jLabel58.setText(String.valueOf(rs.getDouble("ATTENDANCE")));
                  
                 }
                else
                {
                    jLabel58.setText("ATTENDANCE DETAILS NOT FOUND");
                
                }
    
                }
        catch(Exception e)
        {}
        Main.removeAll();
        Main.add(Attendance);
        Main.repaint();
        Main.revalidate();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try
        {
            ResultSet rs;
            Statement stmt=(Project1.con).createStatement();
            //String sql1="select * from Details where Roll='"+r+"'";
            rs=stmt.executeQuery("select * from RESULT where Roll='"+r+"'");   
                if(rs.next())
                {
                    jLabel65.setText(String.valueOf(rs.getInt("Subject1")));
                    jLabel66.setText(String.valueOf(rs.getInt("Subject2")));
                    jLabel67.setText(String.valueOf(rs.getInt("Subject3")));
                    jLabel69.setText(String.valueOf(rs.getInt("Subject4")));
                    jLabel68.setText(String.valueOf(rs.getInt("Total")));
                  jLabel70.setText(String.valueOf(rs.getDouble("PERCENTAGE")));
                  
                 }
                else
                {
                    jLabel70.setText("NO DATA AVAILABLE CONTACT US");
                
                }
    
                }
        catch(Exception e)
        {}
        Main.removeAll();
        Main.add(Marks);
        Main.repaint();
        Main.revalidate();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        Main.removeAll();
        Main.add(Assignment);
        Main.repaint();
        Main.revalidate();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        Main.removeAll();
        Main.add(Menu);
        Main.repaint();
        Main.revalidate();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        Main.removeAll();
        Main.add(Menu);
        Main.repaint();
        Main.revalidate();
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        Main.removeAll();
        Main.add(Menu);
        Main.repaint();
        Main.revalidate();
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        Main.removeAll();
        Main.add(Menu);
        Main.repaint();
        Main.revalidate();
    }//GEN-LAST:event_jLabel6MouseClicked
public void active()
{
    sbar.setVisible(true);
    sbar.setEnabled(true);
    Menu.setVisible(true);
    Menu.setEnabled(false);

}
    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
        active();
    }//GEN-LAST:event_jLabel7MouseClicked

    private void MenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuMouseClicked
        // TODO add your handling code here:
       sbar.setVisible(false);
        
    
        
    }//GEN-LAST:event_MenuMouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
        Main.removeAll();
        Main.add(Menu);
        Main.repaint();
        Main.revalidate();
        sbar.setVisible(false);
        
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
        Main.removeAll();
        Main.add(Settings);
        Main.repaint();
        Main.revalidate();
        sbar.setVisible(false);
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:
        Main.removeAll();
        Main.add(LOGIN);
        Main.repaint();
        Main.revalidate();
        sbar.setVisible(false);
        r="";
        jLabel12.setText("Successfully SIGNOUT");
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        // TODO add your handling code here:
        Main.removeAll();
        Main.add(Menu);
        Main.repaint();
        Main.revalidate();
        
    }//GEN-LAST:event_jLabel13MouseClicked

    private void AttendanceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AttendanceMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_AttendanceMouseClicked

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        // TODO add your handling code here:
        Main.removeAll();
        Main.add(LOGIN);
        Main.repaint();
        Main.revalidate();
        
    }//GEN-LAST:event_jLabel14MouseClicked

    private void jLabel18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseClicked
        // TODO add your handling code here:
        Main.removeAll();
        Main.add(Editor);
        Main.repaint();
        Main.revalidate();
        
    }//GEN-LAST:event_jLabel18MouseClicked

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        // TODO add your handling code here:
        Main.removeAll();
        Main.add(Update);
        Main.repaint();
        Main.revalidate();
    }//GEN-LAST:event_jLabel15MouseClicked

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
        // TODO add your handling code here:
         TreeSet <Details>list2=new TreeSet<>(new MyComparator());
 Filter(list2);
      Main.removeAll();
        Main.add(SearchData);
        Main.repaint();
        Main.revalidate();
    }//GEN-LAST:event_jLabel16MouseClicked

    private void jLabel17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseClicked
        // TODO add your handling code here:
        Main.removeAll();
        Main.add(Delete);
        Main.repaint();
        Main.revalidate();
    }//GEN-LAST:event_jLabel17MouseClicked

    private void jLabel20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel20MouseClicked
        // TODO add your handling code here:
        Main.removeAll();
        Main.add(Editor);
        Main.repaint();
        Main.revalidate();
        jTextField14.setText("");
        jTextField15.setText("");
        jTextField16.setText("");
        jTextField17.setText("");
        jTextField18.setText("");
        jTextField19.setText("");
        jLabel87.setText("");
        
    }//GEN-LAST:event_jLabel20MouseClicked

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jLabel23MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel23MouseClicked
        // TODO add your handling code here:
        Main.removeAll();
        Main.add(Insert);
        Main.repaint();
        Main.revalidate();
    }//GEN-LAST:event_jLabel23MouseClicked

    private void jLabel24MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel24MouseClicked
        // TODO add your handling code here:
        Main.removeAll();
        Main.add(Editor);
        Main.repaint();
        Main.revalidate();
        jTextField1.setText("");
        jTextField5.setText("");
        jTextField6.setText("");
        jTextField7.setText("");
        jLabel84.setText("");
    }//GEN-LAST:event_jLabel24MouseClicked

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jLabel29MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel29MouseClicked
        // TODO add your handling code here:
        Main.removeAll();
        Main.add(Result);
        Main.repaint();
        Main.revalidate();
        
    }//GEN-LAST:event_jLabel29MouseClicked

    private void jLabel32MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel32MouseClicked
        // TODO add your handling code here:
        Main.removeAll();
        Main.add(Insert);
        Main.repaint();
        Main.revalidate();
        jTextField8.setText("");
        jLabel85.setText("");
        jTextField9.setText("");
        jTextField10.setText("");
        jTextField11.setText("");
        jTextField12 .setText("");
        
    }//GEN-LAST:event_jLabel32MouseClicked

    private void jTextField10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField10ActionPerformed

    private void jLabel31MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel31MouseClicked
        // TODO add your handling code here:
        r=jTextField7.getText();
        n=jTextField5.getText();
        m=jTextField1.getText();
        
if(r.equals("")||n.equals("")||jTextField6.getText().equals("")||m.equals(""))
{
    jLabel84.setText("Fill All Fields");
}

else
{
    a=Double.parseDouble(jTextField6.getText());
       int i= Project1.insert(this);
        if(i==0)
        {jLabel84.setText("Succesfully Inserted");}
        else
            jLabel84.setText("Same username already exists");
}
    }//GEN-LAST:event_jLabel31MouseClicked

    private void jLabel37MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel37MouseClicked
        // TODO add your handling code here:
      //  Project1 o=new Project1();
       
            String r1=jTextField12.getText();
           if(r1.equals("")||jTextField8.getText().equals("")||jTextField9.getText().equals("")||jTextField10.getText().equals("")||jTextField11.getText().equals(""))
           {
               if(r1.equals(""))
               jLabel85.setText("Enter roll number");
               else
                   jLabel85.setText("Fill all Subject Fields");

           }
           else
           {
           try
{
    
      
      int sb1=Integer.parseInt(jTextField8.getText());
      int sb2=Integer.parseInt(jTextField9.getText());
      int sb3=Integer.parseInt(jTextField11.getText());
      int sb4=Integer.parseInt(jTextField10.getText());
      int total=sb1+sb2+sb3+sb4;
     
      double percentage;
    percentage =  total*100/400;      
      System.out.println(percentage);     
          PreparedStatement    stmt;
          stmt = (Project1.con).prepareStatement("insert into Result(Roll,Subject1,Subject2,Subject3,Subject4,Total,Percentage)values(?,?,?,?,?,?,?)");
                stmt.setString(1,r1);
                stmt.setInt(2,sb1);
                stmt.setInt(3,sb2);
                stmt.setInt(4,sb3);
                stmt.setInt(5,sb4);
                stmt.setInt(6,total);
                stmt.setDouble(7,percentage);
              stmt.executeUpdate();
              jLabel85.setText("Succesfully Inserted");
}
catch(Exception e)
{
    jLabel85.setText("Already existing data go to update");
}
           
           
           
           }
        
        
        
        
    }//GEN-LAST:event_jLabel37MouseClicked

    private void jLabel22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel22MouseClicked
        // TODO add your handling code here:
        if(jTextField4.getText().equals(""))
            jLabel40.setText("Enter Roll No.");
        else
        {
        try
        {
        String mo=jTextField4.getText();
        String sql1="select * from Details where Roll='"+mo+"'";
        String sql3="select * from Result where Roll='"+mo+"'";
        Statement stmt=(Project1.con).createStatement();
               ResultSet rs=stmt.executeQuery(sql1);
                if(rs.next())
                {
                    
                    jLabel40.setText("DETAILS DATA FOUND");
                    //System.out.println("NAME is "+rs.getString(1));
                    //System.out.println("MOBILE is "+rs.getString(2));
                   
                    
                    String sql2="delete from Details where Roll='"+mo+"'";
                    stmt.executeUpdate(sql2);
                }
                else
                {
                
                jLabel40.setText("DETAILS DATA NOT FOUND");
                
                
                }
                rs=stmt.executeQuery(sql3);
                if(rs.next())
                {
                jLabel41.setText("RESULT DATA FOUND");
                    String sql4="delete from RESULT where Roll='"+mo+"'";
                    stmt.executeUpdate(sql4);
                }
                else
                {
                    jLabel41.setText("RESULT DATA NOT FOUND");
                
                }
                
        }
        catch(Exception e)
        {
        
        }
        }
        
    }//GEN-LAST:event_jLabel22MouseClicked

    private void jLabel44MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel44MouseClicked
        // TODO add your handling code here:
        Main.removeAll();
        Main.add(Editor);
        Main.repaint();
        Main.revalidate();
        for(int i=model.getRowCount()-1;i>=0;i--)
        model.removeRow(i);
    }//GEN-LAST:event_jLabel44MouseClicked
void Filter(TreeSet list)
{
        
        try
        {
        String ps="select * from details";
        PreparedStatement stmt=Project1.con.prepareStatement(ps);
        ResultSet rs=stmt.executeQuery();
        while(rs.next())
        {
         Details dn=new Details(rs.getDouble(4),rs.getString(2),rs.getString(3),rs.getString(1),rs.getString(5));
        list.add(dn);
        }
        String ps1="select * from result";
        PreparedStatement stmt1=Project1.con.prepareStatement(ps1);
        ResultSet rs1=stmt1.executeQuery();
        l1: while(rs1.next())
        {
        Iterator itr=list.iterator();
        while(itr.hasNext())
        {
        Details rp=(Details)itr.next();
        if(rp.roll.equals(rs1.getString(1)))
        {
         rp.Detail(rs1.getInt(2),rs1.getInt(3),rs1.getInt(4),rs1.getInt(5),rs1.getInt(6),rs1.getDouble(7));
         continue l1;
        }
        }
        }
        }
        
        catch(Exception e)
        {}
        Iterator itr2=list.iterator();
        while(itr2.hasNext())
        {
            Details d=(Details)itr2.next();
        model.addRow(new Object[]{  d.roll,d.name,d.mobile,d.attendance,d.dues,d.s1,d.s2,d.s3,d.s4,d.t,d.p                 });
        
        }
        
        
}



void Filter2(TreeSet<Details> r)
{
try
        {
        String ps="select * from result";
        PreparedStatement stmt=Project1.con.prepareStatement(ps);
        ResultSet rs=stmt.executeQuery();
        while(rs.next())
        {
         Details dn=new Details();
         dn.Detail(rs.getInt(2),rs.getInt(3),rs.getInt(4),rs.getInt(5),rs.getInt(6),rs.getDouble(7));
         dn.Roll_No(rs.getString(1));
        r.add(dn);
        }
        String ps1="select * from details";
        PreparedStatement stmt1=Project1.con.prepareStatement(ps1);
        ResultSet rs1=stmt1.executeQuery();
        l1: while(rs1.next())
        {
        Iterator itr=r.iterator();
        while(itr.hasNext())
        {
        
        Details rp=(Details)itr.next();
   
        if(rp.roll.equals(rs1.getString(1)))
        {
            
           rp.DetailMarks(rs1.getDouble(4),rs1.getString(2),rs1.getString(3),rs1.getString(1),rs1.getString(5));
         continue l1;
        }
        }
        }
        }
        
        catch(Exception e)
        {}
        Iterator itr2=r.iterator();
        while(itr2.hasNext())
        {
            Details d=(Details)itr2.next();
        model.addRow(new Object[]{  d.roll,d.name,d.mobile,d.attendance,d.dues,d.s1,d.s2,d.s3,d.s4,d.t,d.p                 });
        }
}




    private void jTextField17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField17ActionPerformed

    private void jTextField18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField18ActionPerformed

    private void jTextField15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField15ActionPerformed

    private void jLabel51MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel51MouseClicked
        // TODO add your handling code here:
        try
        {
       String r1=jTextField19.getText();
        a=Double.parseDouble(jTextField14.getText());
        String update="update Details set Attendance=? where Roll='"+r1+"'";
       PreparedStatement rs;
            rs = (Project1.con).prepareStatement(update);
       rs.setDouble(1,a);
       rs.executeUpdate();
       jLabel87.setText("UPDATED!");
        }
        catch(Exception e)
        {
        jLabel87.setText("PLEASE ENTER ROLL NO. & ATTANDANCE");
        }
    }//GEN-LAST:event_jLabel51MouseClicked

    private void jLabel52MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel52MouseClicked
        // TODO add your handling code here:
        try
        {
       String r1=jTextField19.getText();
        String update="update RESULT set Subject1=?,Subject2=?,Subject3=?,Subject4=?,Total=?,Percentage=? where Roll='"+r1+"'";
       PreparedStatement rs;
       int total=Integer.parseInt(jTextField15.getText())+Integer.parseInt(jTextField16.getText())+Integer.parseInt(jTextField17.getText())+Integer.parseInt(jTextField18.getText());
       double percentage=total*100/400;    
       rs = (Project1.con).prepareStatement(update);
            rs.setInt(1,Integer.parseInt(jTextField15.getText()));
            rs.setInt(2,Integer.parseInt(jTextField16.getText()));
            rs.setInt(3, Integer.parseInt(jTextField17.getText()));
            rs.setInt(4, Integer.parseInt(jTextField18.getText()));
            rs.setInt(5,total);
            rs.setDouble(6,percentage);
       rs.executeUpdate();
        jLabel87.setText("UPDATED!");
        }
        catch(Exception e)
        {
        jLabel87.setText("PLEASE ENTER ROLL NO. & fill all subjects");
        }
       
    }//GEN-LAST:event_jLabel52MouseClicked

    private void jTextField20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField20ActionPerformed

    private void jLabel73MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel73MouseClicked
        // TODO add your handling code here:
        try
        {
             ResultSet rs1;
       String sql2="select * from Security where Roll='"+r+"'";
       Statement stmt=(Project1.con).createStatement();
            rs1=stmt.executeQuery(sql2);
        rs1.next();
        if((jTextField21.getText()).equals(jTextField22.getText()))
        {
        if((rs1.getString(2)).equals(jTextField20.getText()))    
        {
            String update="update SECURITY set PASSWORD=? where Roll='"+r+"'";
       PreparedStatement rs;
            rs = (Project1.con).prepareStatement(update);
            
       rs.setString(1,jTextField22.getText());
       rs.executeUpdate();
       jLabel75.setText("PASSWORD CHANGED SUCCESSFULLY");
        }
        else
        {
        
        
        jLabel75.setText("OLD PASSWORD IS NOT CORRECT");
        
        }
        }
        else
        {
        jLabel75.setText("NEW and CONFIRM PASSWORD NOT MATCH");
        
        }
        }
        catch(Exception e)
        {}
    }//GEN-LAST:event_jLabel73MouseClicked

    private void jLabel79MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel79MouseClicked
        // TODO add your handling code here:
         Main.removeAll();
        Main.add(INSERTDUES);
        Main.repaint();
        Main.revalidate();
    }//GEN-LAST:event_jLabel79MouseClicked

    private void jLabel80MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel80MouseClicked
        // TODO add your handling code here:
         Main.removeAll();
        Main.add(Editor);
        Main.repaint();
        Main.revalidate();
        jTextField23.setText("");
        jTextField24.setText("");
        jLabel86.setText("");
    }//GEN-LAST:event_jLabel80MouseClicked

    private void jLabel82MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel82MouseClicked
        // TODO add your handling code here:
        if(jTextField24.getText().equals("")||jTextField23.getText().equals(""))
        {
        
        if(jTextField24.getText().equals(""))
            jLabel86.setText("Enter Roll no.");
        
        else
            jLabel86.setText("Enter Dues");
        
        
        
        
        }
        else
        {
        try
        {
      
       
        String update="update Details set DUES=? where Roll='"+jTextField24.getText()+"'";
       PreparedStatement rs;
            rs = (Project1.con).prepareStatement(update);
       rs.setString(1,jTextField23.getText());
        jLabel86.setText("UPDATED!");
       rs.executeUpdate();
        }
        catch(Exception e)
        {}
       
        }
    }//GEN-LAST:event_jLabel82MouseClicked

    private void jTextField19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField19ActionPerformed

    private void jTextField8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField8MouseExited
        // TODO add your handling code here:
     
    }//GEN-LAST:event_jTextField8MouseExited

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        String c=jComboBox1.getItemAt(jComboBox1.getSelectedIndex());
        for(int i=model.getRowCount()-1;i>=0;i--)
        model.removeRow(i);
        if(c.equals("Attendance")||(c.equals("Roll")))
        {
            
            if(c.equals("Roll"))
            {
            
             TreeSet <Details>list1=new TreeSet<>(new MyComparator());
            Filter(list1);
        }
            else
            {
            
            TreeSet <Details>list1=new TreeSet<>(new MyComparator1());
            Filter(list1);
            
            
            }
        }
        else
        {
          
        if(c.equals("Marks"))
        {
        TreeSet <Details>list1=new TreeSet<>(new MyComparator3());
Details[] des=new Details[200];
          Filter2(list1);
        }
        else
        {
       TreeSet <Details>list1=new TreeSet<>(new MyComparator4());
            Filter(list1);
        
        
        }
        
        
        
        
        }
        
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jTextField23KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField23KeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(!Character.isDigit(c)||(c==KeyEvent.VK_S))
        {
        getToolkit().beep();
        evt.consume();
        }
    }//GEN-LAST:event_jTextField23KeyTyped

    private void jTextField24KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField24KeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(!Character.isDigit(c)||(c==KeyEvent.VK_S))
        {
        getToolkit().beep();
        evt.consume();
        }
    }//GEN-LAST:event_jTextField24KeyTyped

    private void jTextField19KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField19KeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(!Character.isDigit(c)||(c==KeyEvent.VK_S))
        {
        getToolkit().beep();
        evt.consume();
        }
    }//GEN-LAST:event_jTextField19KeyTyped

    private void jTextField15KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField15KeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(!Character.isDigit(c)||(c==KeyEvent.VK_S))
        {
        getToolkit().beep();
        evt.consume();
        }
    }//GEN-LAST:event_jTextField15KeyTyped

    private void jTextField16KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField16KeyTyped
char c=evt.getKeyChar();
        if(!Character.isDigit(c)||(c==KeyEvent.VK_S))
        {
        getToolkit().beep();
        evt.consume();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField16KeyTyped

    private void jTextField17KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField17KeyTyped
char c=evt.getKeyChar();
        if(!Character.isDigit(c)||(c==KeyEvent.VK_S))
        {
        getToolkit().beep();
        evt.consume();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField17KeyTyped

    private void jTextField18KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField18KeyTyped
char c=evt.getKeyChar();
        if(!Character.isDigit(c)||(c==KeyEvent.VK_S))
        {
        getToolkit().beep();
        evt.consume();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField18KeyTyped

    private void jTextField14KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField14KeyTyped
char c=evt.getKeyChar();
       
        if(!Character.isDigit(c)||(c==KeyEvent.VK_SPACE))
        {
            if(c=='.')
            {}
            else
            {
        getToolkit().beep();
        evt.consume();
            }
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField14KeyTyped

    private void jTextField12KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField12KeyTyped
char c=evt.getKeyChar();
        if(!Character.isDigit(c)||(c==KeyEvent.VK_S))
        {
        getToolkit().beep();
        evt.consume();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField12KeyTyped

    private void jTextField8KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField8KeyTyped
char c=evt.getKeyChar();
        if(!Character.isDigit(c)||(c==KeyEvent.VK_S))
        {
        getToolkit().beep();
        evt.consume();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8KeyTyped

    private void jTextField9KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField9KeyTyped
char c=evt.getKeyChar();
        if(!Character.isDigit(c)||(c==KeyEvent.VK_S))
        {
        getToolkit().beep();
        evt.consume();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9KeyTyped

    private void jTextField11KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField11KeyTyped
char c=evt.getKeyChar();
        if(!Character.isDigit(c)||(c==KeyEvent.VK_S))
        {
        getToolkit().beep();
        evt.consume();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField11KeyTyped

    private void jTextField10KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField10KeyTyped
char c=evt.getKeyChar();
        if(!Character.isDigit(c)||(c==KeyEvent.VK_S))
        {
        getToolkit().beep();
        evt.consume();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField10KeyTyped

    private void jTextField6KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField6KeyTyped
char c=evt.getKeyChar();
       
        if(!Character.isDigit(c)||(c==KeyEvent.VK_SPACE))
        {
            if(c=='.')
            {}
            else
            {
        getToolkit().beep();
        evt.consume();
            }
        }         // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6KeyTyped

    private void jTextField7KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField7KeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
       
        if(!Character.isDigit(c)||(c==KeyEvent.VK_SPACE))
        {
            
           
        getToolkit().beep();
        evt.consume();
            
        }      
    }//GEN-LAST:event_jTextField7KeyTyped

    private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
       
        if(!Character.isDigit(c)||(c==KeyEvent.VK_SPACE))
        {
            if(c=='.')
            {}
            else
            {
        getToolkit().beep();
        evt.consume();
            }
        }      
    }//GEN-LAST:event_jTextField1KeyTyped

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField5KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5KeyTyped

    private void jTextField23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField23ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField23ActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Assignment;
    private javax.swing.JPanel Attendance;
    private javax.swing.JPanel Delete;
    private javax.swing.JPanel Dues;
    private javax.swing.JPanel Editor;
    private javax.swing.JPanel INSERTDUES;
    private javax.swing.JPanel Insert;
    private javax.swing.JPanel LOGIN;
    private javax.swing.JPanel Main;
    private javax.swing.JPanel Marks;
    private javax.swing.JPanel Menu;
    private javax.swing.JPanel Result;
    private javax.swing.JPanel SearchData;
    private javax.swing.JPanel Settings;
    private javax.swing.JPanel Update;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JLabel jLabel85;
    private javax.swing.JLabel jLabel86;
    private javax.swing.JLabel jLabel87;
    private javax.swing.JLabel jLabel88;
    private javax.swing.JLabel jLabel89;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel90;
    private javax.swing.JLabel jLabel91;
    private javax.swing.JLabel jLabel92;
    private javax.swing.JLabel jLabel93;
    private javax.swing.JLabel jLabel94;
    private javax.swing.JLabel jLabel95;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTextField jTextField23;
    private javax.swing.JTextField jTextField24;
    private javax.swing.JPasswordField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JPanel sbar;
    // End of variables declaration//GEN-END:variables
}
